# Generated by Django 6.1.1 on 2026-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='options',
        ),
        migrations.AddField(
            model_name='listing',
            name='LastUpdated',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='ticker',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='undefined', max_length=120),
        ),
    ]
