# Generated by Django 6.1.1 on 2026-09-21 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0002_remove_listing_options_listing_lastupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
